language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  chrome: stable
  firefox: latest
  sauce_connect: true
cache:
  directories:
  - bower_components
  - node_modules
before_script:
- npm install -g polymer-cli
- polymer install
script:
- polymer lint
- xvfb-run polymer test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: lykgAuGvrQiA5JxIj8t86ZZzXc7kkrlNieOpkBlNluF1OLca43hNUrOuApOEvm1QOMm8nKPLN5KoCVy5Qhw3zB8i6HJ0fPvBjhbmDM4mXghnHO1I6Uv5pqG8ckjefZeuEpuvZBG4NW4cLuamAhRcPw0OVJ+YBPeFmYUTXix5nUXL+UAeqONxLEvavnhLnbFHnc2doZRmKwQ4q1bCU/D89ME3FWHw+LYN0Nu5DgXg7LhHNFzY8xJxkgOrbdo5ZMZrC0NP9otgLClTuaBXKMNyZouehmjG3Bj0ATMIZFY9Slnc5KEZOTtYill3V0YkNOazXbDQw2s9WAh4IY9njNILXQPqLyt/ZjZjpGFLcR59qkHb6s9ryZXEkvjLzpo1vaiBi9XmtR+i2GY6yUwzjQJooPjEC3u2wvhHV06cRRgcMT6vQgHAqhgxXzA6BMpNjau2IqglwtohXtTO+a9G+VKzW06pCR2Ia6ACI5mXaK1AOd0ancwdw+rgWRxQPRnI3227vKKCv0GA5NnOrrg5I3Mo+KBFMbPV/wqKiC81iBOqMDrZR6Kt/Dmee2Kqfl88046250rCev4Hcbgw1uzNMac6GDEwug3FHKWiyhLXx1Zjr+1cOCoul3ufGWiLy4Uu/Oqp0YnxTZfAyVPlvr8SZBXaqLQ0oT7Cjxm1inVY6BMU6v4=
  - secure: s29yZVjzLjLJNNCsUokWc+JMOumyJcjhnO/jd2Ruwos9F5nxfnLV9aVUTYHOJHj941mm56djYpeCUL65rF686mm067ZRTowGxOB+iQqc4jHxSl3MqSEaI40d2e6DeYtEXdWjVHW3ka9TniLttQ79WTDV+8iG2plZ7jjCUH/dB+JWXO/nwKJvuly49DwDSym8vAFMKCevljI2H7Mo9K3tDtqM+/j4Fv0Y5yU0e7/2upKZ/52l2dxklv5KqHT4bjyT2cos+mLxafgBkZwN3scRGaXLZyQvtEGfu3i1I1veMbSahmNeRIfGm2jUH410f0T9tTOSK4nw2CEVxLZcbn3qlVTqsOD3mgRNtPnOZqS3CjQNd/dfwoHjpantE8hK4oZFEqy/hsFp0lAWUQqWNiZKg8aSV8uvs6sRxU7gQhBuEkgvisvm8JmAfRo2WLrz0r+H8e3cRlKyOO34nigZb8y0MFmvIAut3faaaTeff1kp9eqnaQuFFqAErLqvETaf6A2cw3iCP2erir57MqaHGDzMGhINGulQT4tpszUVZsuR0cdREy3PKEbZDdlYYeXeWBVRpF5GgIDUmP5nxShDBcw8ROzKilSTX1yEb0e+Uud46D+2cH3RA7bV2thKSnbDquDgSA+8PuMOqoGqOQ+IRbYrYTG82g2pHDeZlONhMDdQSlI=
deploy:
  api_key:
    secure: oITJNXisiVyi3lkIhYLJtnF0Vtu1iFUUY1SgJslBJ4A3UBKbJbnUpwHC15GXVZFpn8mS2SNYZGeMnvTXdU5WKHJU7BfMDCG3tF7wUlVU1mUqpMBQF91Q1h1pZkFgA8OJePdVErGwlrIFuujP+p3mMLqqRETxqlFHhVoykn0RV1f1iC4Ikk+yfcFpi8ejMDrSZcAgqdBEp8UmnoIsCAt3Fyp46nwQ1xBmIKW6WKmv/VwsiKmk4f8Wyiyf6Kj1CQHzOOgdTlh14ODFtUZfq2NCbOK7cj5UcRtEuJfw9BH3eUo9XpPwzvfncTL5+3tExTi5yuuw29sWCSwlIL0dw+5cTiNda583TyQJKktajoVm3ttGB/Y4oMZJQi15QjpvInNiKA0uchmbRC0rpGG7P+mz/hFqYJ89nHv55RM5qsKV+86XhfIYPPHwaNF/aK9UOcRrFZiLcKBngbAHuwg3ndAJ0NNPZ767ZmidSIXknOQ8AL5V+YIb/sk0k5hb6L0UHc5Q8v1dyBaBb6i/GXAcxjx8n8Cx/hC8jOV9PjmC8DGafMjYLH+CQRP9y9bo35FHV4fxYlAAeuTj4onoyf5bma6/k/cJpgGkjXzLHawaHsaNdryFOSMcQrnC9yhiG890nYVWyl0jn2F28MB1pC1J4ms0taVbZYYYormOl1I7iC9lD54=
